name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install ruff
    - name: Run format check
      run: |
        source .venv/bin/activate
        ruff format --check .
        ruff check .
    - name: Unit tests
      id: unit-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: 'source .venv/bin/activate'
    - name: Setup Secret Test
      id: setup-secret-test
      run: |
        rm -r tests/*
        echo ${{ secrets.HIDDEN_TEST }} > tests/test_secret.py
    - name: Secret unit tests
      id: secret-unit-tests
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: 'source .venv/bin/activate'
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UNIT-TESTS_RESULTS: "${{steps.unit-tests.outputs.result}}"
      with:
        runners: unit-tests
