name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Manual unit tests
      id: manual-unit-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Manual unit tests
        setup-command: ''
        command: pip install -r requirements.txt && pytest
        timeout: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MANUAL-UNIT-TESTS_RESULTS: "${{steps.manual-unit-tests.outputs.result}}"
      with:
        runners: manual-unit-tests
